# Generated by Django 2.2 on 2022-05-03 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=70)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1234567890'.", regex='^\\+?1?\\d{9,15}$')])),
                ('sympton', models.TextField()),
                ('lastTreatment', models.CharField(max_length=100)),
                ('newComplaints', models.TextField()),
                ('changeMedication', models.CharField(max_length=50)),
                ('changeLastVisit', models.CharField(max_length=50)),
                ('sweat', models.CharField(max_length=50)),
                ('appetite', models.CharField(max_length=50)),
                ('sleep', models.CharField(max_length=50)),
                ('tinnitus', models.CharField(max_length=50)),
                ('mouth', models.CharField(max_length=50)),
                ('digestion', models.CharField(max_length=50)),
                ('stool', models.CharField(max_length=50)),
                ('eyes', models.CharField(max_length=50)),
                ('teeth', models.CharField(max_length=50)),
                ('sexualActivities', models.CharField(max_length=50)),
                ('swelling', models.CharField(max_length=50)),
                ('thirst', models.CharField(max_length=50)),
                ('urine', models.CharField(max_length=50)),
                ('nose', models.CharField(max_length=50)),
                ('throat', models.CharField(max_length=50)),
                ('caseNumber', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
