# Generated by Django 2.2 on 2022-05-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='newComplaints',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sympton',
            field=models.TextField(default='N/A'),
        ),
    ]
