# Generated by Django 2.2 on 2022-05-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0003_patient_diagnosisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lastTreatment',
            field=models.CharField(choices=[('Same', 'Same result'), ('Better', 'Feel better'), ('Worse', 'Worse')], default='Better', max_length=100),
        ),
    ]
