# Generated by Django 2.2 on 2022-05-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0004_auto_20220509_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lastTreatment',
            field=models.CharField(default='Better', max_length=50),
        ),
    ]
