# Generated by Django 2.2 on 2022-05-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0006_auto_20220509_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lastVisitComment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.CharField(default='better', max_length=10),
        ),
    ]
