# Generated by Django 2.2 on 2022-05-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0007_auto_20220509_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='newComplaintsComment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.CharField(default='N/A, please ask', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='newComplaints',
            field=models.CharField(default='N/A, please ask', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sympton',
            field=models.TextField(default='N/A, please ask'),
        ),
    ]
