# Generated by Django 2.2 on 2022-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0008_auto_20220509_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lastVisitComment',
            field=models.TextField(blank=True, default='N/A, please ask'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='newComplaintsComment',
            field=models.TextField(blank=True, default='N/A, please ask'),
        ),
    ]
