# Generated by Django 2.2 on 2022-05-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0011_auto_20220509_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastVisitComment',
            field=models.TextField(blank=True),
        ),
    ]
