# Generated by Django 2.2 on 2022-05-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0013_auto_20220509_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='unknown', max_length=20, null=True),
        ),
    ]
