# Generated by Django 2.2 on 2022-05-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0014_auto_20220509_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
