# Generated by Django 2.2 on 2022-05-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0016_auto_20220509_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tongueImg',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
