# Generated by Django 2.2 on 2022-05-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0020_auto_20220512_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientimg',
            old_name='img',
            new_name='imgs',
        ),
        migrations.AlterField(
            model_name='patientimg',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_imgs', to='firstTrial.Patient'),
        ),
    ]
