# Generated by Django 2.2 on 2022-05-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0022_auto_20220512_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imges/'),
        ),
    ]
