# Generated by Django 2.2 on 2022-05-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0023_auto_20220512_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sympton',
            field=models.TextField(blank=True),
        ),
    ]
