# Generated by Django 2.2 on 2022-05-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0026_auto_20220512_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='agreementCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='verifyStatus',
            field=models.BooleanField(default=False),
        ),
    ]
