# Generated by Django 2.2 on 2022-05-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0028_patient_diagnosisinitial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='changeLastVisit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='changeMedication',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lastVisit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lastVisitComment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='newComplaints',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='newComplaintsComment',
        ),
    ]
