# Generated by Django 2.2 on 2022-05-23 20:58

from django.db import migrations, models
import firstTrial.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0029_auto_20220523_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='face',
            field=models.ImageField(default=0, upload_to=firstTrial.models.upload_location),
        ),
        migrations.AddField(
            model_name='patient',
            name='leftEye',
            field=models.ImageField(default=0, upload_to=firstTrial.models.upload_location),
        ),
        migrations.AddField(
            model_name='patient',
            name='rightEye',
            field=models.ImageField(default=0, upload_to=firstTrial.models.upload_location),
        ),
        migrations.AddField(
            model_name='patient',
            name='tongueCoat',
            field=models.ImageField(default=0, upload_to=firstTrial.models.upload_location),
        ),
    ]
