# Generated by Django 2.2 on 2022-05-23 21:39

from django.db import migrations, models
import firstTrial.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0031_auto_20220523_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfiles',
            name='files',
        ),
        migrations.AddField(
            model_name='patientfiles',
            name='file',
            field=models.FileField(default=0, upload_to=firstTrial.models.upload_location),
        ),
    ]
