# Generated by Django 2.2 on 2022-05-24 18:22

from django.db import migrations, models
import firstTrial.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0032_auto_20220523_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfiles',
            name='file',
            field=models.FileField(default=0, upload_to=firstTrial.models.user_directory_path),
        ),
    ]
