# Generated by Django 2.2 on 2022-05-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0033_auto_20220524_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='verifyStatus',
        ),
    ]
