# Generated by Django 3.2.13 on 2022-06-06 20:25

from django.db import migrations, models
import firstTrial.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0034_remove_patient_verifystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='face',
            field=models.ImageField(upload_to=firstTrial.models.upload_location),
        ),
        migrations.AlterField(
            model_name='patient',
            name='leftEye',
            field=models.ImageField(upload_to=firstTrial.models.upload_location),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rightEye',
            field=models.ImageField(upload_to=firstTrial.models.upload_location),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tongueCoat',
            field=models.ImageField(upload_to=firstTrial.models.upload_location),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='file',
            field=models.FileField(upload_to=firstTrial.models.user_directory_path),
        ),
    ]
