# Generated by Django 3.2.13 on 2022-06-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0038_auto_20220619_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientform',
            name='lungResult',
            field=models.TextField(blank=True),
        ),
    ]
