# Generated by Django 3.2.13 on 2022-07-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTrial', '0039_patientform_lungresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientform',
            name='gallbladderResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='heartResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='kidneyResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='large_intestineResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='liverResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='pericardiumResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='san_jiaoResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='small_intestineResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='spleenResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='stomachResult',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='urinaryBladderResult',
            field=models.TextField(blank=True),
        ),
    ]
